### ISSUE TITLE
Add a json result format button 

### ISSUE THREAD

**Issue by ginus** [ddavison/rest-client#10]
Most respone is json this function is very useful.

**Comment by javaguirre** [comment]
What do you mean exactly? Having the json syntax and indentation in a better way?

I think It should be done automatically, It's a feauture everybody would want IMO.

I think It could check if the response is json, and if It is, just format It accordingly.

I'll check how could be done.

**Comment by ddavison** [comment]
@javaguirre  did #23  close this one?

**Comment by javaguirre** [comment]
@ddavison I added format to the output, not syntax highlighting, that's a bit trickier, the issue was generic, so It depends if we were counting on having also syntax highlighting on the formatting. What do you think?

**Comment by ddavison** [comment]
I never really intended having syntax highlighting in the result window.. that's mostly what the "open in separate editor" was for

**Comment by javaguirre** [comment]
Ok, It's for the best, so I am gonna close It. :+1:

**Comment by ddavison** [comment]
well done on the formatting @javaguirre  :)  that's excellent functionality that will be loved.
