### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by gonzaloadrio** [ddavison/rest-client#17]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Gonzalo\AppData\Local\atom\app-0.182.0\resources\app\src\atom.js:54:11)
Object.activate (C:\Users\Gonzalo\.atom\packages\rest-client\lib\rest-client.coffee:18:9)
```

**Comment by ddavison** [comment]
fixed in 6b74d29ed79e858a5c4de35d4e8bd7f3854f5509
