### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by ddavison** [ddavison/rest-client#22]
just realized that this repo has no tests...  a no-no!  :(

we should add tests.

**Comment by javaguirre** [comment]
:+1:

**Comment by javaguirre** [comment]
Would be nice to activate the project in https://travis-ci.org/

I did It with my fork to check if It was working, we could add the Travis badge to show the people how "trustworthy" we are. :-)

**Comment by ddavison** [comment]
should already be:

https://travis-ci.org/ddavison/rest-client

**Comment by javaguirre** [comment]
Nice! :tada:

**Comment by ddavison** [comment]
just added the badge :smile:  I'll create a CONTRIBUTING.md file denoting that any features should have tests written for them, *then* close this :)

**Comment by javaguirre** [comment]
:+1:

**Comment by ddavison** [comment]
done :) also added [.editorconfig](https://github.com/ddavison/rest-client/tree/master/.editorconfig)

**Comment by javaguirre** [comment]
:+1:
