### ISSUE TITLE
Copy / Paste not working correctly

### ISSUE THREAD

**Issue by mithataydogmus** [ddavison/rest-client#26]
Hello,

When I copy strings from any other source and paste them inside RestClient, it duplicates the string. Always pasting 2 times and doing it in "every" input.

I also uninstalled / reinstalled package, problem continues. Tried to dig into code but couldn't find the problem easily.

Atom 1.3.1
OSX El Capitan 10.11.1

**Comment by ddavison** [comment]
I'll investigate this when I can - will be AFK most all day today :(   Thanks for letting me know

**Comment by mithataydogmus** [comment]
It's totally fine, I have no rush. Except this problem, RestClient working fine for me. If you tell me how to handle to problem or at least give me a clue about it I'll try to help too.

**Comment by ragboyjr** [comment]
:+1: every time I copy and paste, it pastes the string twice.

**Comment by ddavison** [comment]
pushed in version 0.5.1 :+1:

**Comment by ragboyjr** [comment]
Looks great thanks! :+1:
