### ISSUE TITLE
Encode payload/Decode payload should be on a different line

### ISSUE THREAD

**Issue by thatchej** [ddavison/rest-client#30]
![Image Example](https://cloud.githubusercontent.com/assets/1555889/13761103/df5a2996-e9f3-11e5-8f57-4b99ebc81dd5.png)

I just started using this plugin and noticed that the current design of this looks pretty strange. I'm not familiar with CoffeeScript so I can't submit a pull request, but it seems to be in the file `/lib/rest-client-view.coffee` lines 70-72.

**Comment by ddavison** [comment]
might be prettier with a pipe between them rather than separate lines

**Comment by thatchej** [comment]
@ddavison yeah that would look great too!

**Comment by ddavison** [comment]
fixed in 8132c07cbbacaf605e4a4d847f2d49206aaaf773 :)  thanks :+1:

**Comment by ddavison** [comment]
we'll push a new version soon.  after the save-load-requests branch gets merged in
