### ISSUE TITLE
proxy configuration

### ISSUE THREAD

**Issue by deq9z** [ddavison/rest-client#32]
GET http://www.google.ca
result pane:    Error: connect ETIMEDOUT XXX.XXX.XXX.XXX:80

I have configured atom.io to leverage the corporate proxy, have no problems connecting outbound to install packages, however; running into a timeout using rest-client package.  I am speculating that it is due to no proxy configuration in the code.

**Comment by ddavison** [comment]
since we use request, it should be a simple fix:

https://www.npmjs.com/package/request#proxies

**Comment by deq9z** [comment]
thanks for getting back so quickly, I will try it out!

**Comment by ddavison** [comment]
this may be on our side @deq9z :)  not sure you can solve it yourself through the UI.  i was commenting that for the developers of rest-client ;)

**Comment by deq9z** [comment]
yeah, I was looking in the UI code, then in the atom/package/rest-client/node_modules/request/index.js code to see if I could inject it there locally for getting myself up & running.

**Comment by javaguirre** [comment]
This would be nice for starting the **Advanced options** partial view. :-)

**Comment by cluoma** [comment]
Running into the same issue. Any news on this?

**Comment by javaguirre** [comment]
Hi! I'll take a look.
