### ISSUE TITLE
how may I encode basic authentication (login:password)

### ISSUE THREAD

**Issue by ygol** [ddavison/rest-client#46]

**Comment by javaguirre** [comment]
You can use the [`Authorization` header](https://docs.oracle.com/cd/E24191_01/common/tutorials/authn_http_basic.html), like:

![screen shot 2016-08-17 at 11 55 37](https://cloud.githubusercontent.com/assets/488556/17732351/8c5ed55e-6471-11e6-9129-5269078178ac.png)
