### ISSUE TITLE
Put response panel to right will be better

### ISSUE THREAD

**Issue by zhiquan-yu** [ddavison/rest-client#56]
like this, so we can make better use of space, and do not have to scroll down to see the result.
![response to right](http://ww4.sinaimg.cn/large/801b780agw1f7mflr5lsij21740q3tda.jpg)

**Comment by ddavison** [comment]
👍   this would be so much better.  i'll start on this now, unless somebody else beats me to it! 😄

**Comment by ddavison** [comment]
we just need to make sure this is responsive.  you clearly have a gigantic display.  having it split on lesser resolution monitors may look very restricted and tiny.

**Comment by ddavison** [comment]
pushed to version `v1.2.3`   you may update the package from atom

**Comment by zhiquan-yu** [comment]
Thank you! Look better now, and it's responsive.

**Comment by amberlionk** [comment]
Hello, could somebody tell me how to move "Response pane" to the right?
![capture](https://user-images.githubusercontent.com/29119723/47283082-677b5680-d5ea-11e8-8340-1c9047b9fda3.PNG)

**Comment by amberlionk** [comment]
Sorry, my bad.
I meant - to the left.
In module styles declared that "Response block" is responsive. But it depends from full Atom window width.
When you open rest-client in right pane, to have 2 panes on screen (in one Atom window) - response block does not act responsive and stays at the right.
When you minimize Atom window - it moves to the left.
But for Atom opened for full screen - it looks bad.
Atom version 1.31.2 x64. look on screen
![capture2](https://user-images.githubusercontent.com/29119723/47416400-52373100-d77e-11e8-99f7-b3b7e418b594.PNG)

**Comment by ddavison** [comment]
ahh yes.  i understand now.  did you want to try your hand on a pull request, @amberlionk :)

**Comment by amberlionk** [comment]
I could try, but im noob in making packages for Atom. I found that styles are in styles\rest-client.less file.
Is there som plugin which can open rest-client pane in browser(or somewhere), so i could inspect it, to look on HTML structure and try to play with styles?

**Comment by ddavison** [comment]
you have the exact same inspection tools that chrome has (as atom is built on electron!)

<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> - for mac
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> - for windows / linux
