### ISSUE TITLE
How to send cookie?

### ISSUE THREAD

**Issue by makingoff** [ddavison/rest-client#6]
How to send cookie?

**Comment by ddavison** [comment]
course it's ok with me!  thanks @javaguirre !

**Comment by javaguirre** [comment]
@makingoff Could you please try with the new version (0.3.0) so we could see if the fix works for you?

Thanks!

**Comment by makingoff** [comment]
@javaguirre could you take me example of yours? Screenshot would be awesome.

**Comment by makingoff** [comment]
@javaguirre thank you. It works with
```
Cookie: name=makingoff
```

**Comment by javaguirre** [comment]
Thank you, but you are right, we need more information in the README so the people would know how it works.
