### ISSUE TITLE
Problem to perform a POST request with Payload

### ISSUE THREAD

**Issue by silviofernandesrd** [ddavison/rest-client#61]
Hi guys, okay?

I updated the "rest-client" to latest version (1.2.4), and I can't perform a POST request with Payload, generating the error attached.

![error-request-post-with-payload](https://cloud.githubusercontent.com/assets/20071230/18601211/e9d665c0-7c37-11e6-84de-53cbbc4d7595.png)

I solved it rolling back to 1.2.2.

regards

**Comment by ddavison** [comment]
i think you meant to log this [here https://github.com/rest-client/rest-client](https://github.com/rest-client/rest-client) ?
