### ISSUE TITLE
Save to file

### ISSUE THREAD

**Issue by netsi1964** [ddavison/rest-client#64]
Perhaps I am missing something, but the `save` button will not save *the requested data*?
If I am wrong, where do I find the saved data?

If the feature does not exist - I would love to see such a feature: `save to file` which would allow you to save the requested data to a file, perhaps with the content in one file and the headers in another file.

Thank you for a great package btw :-)

**Comment by ddavison** [comment]
I believe you are talking about the "Open in external editor" functionality?    If you click that, it will save the requested data in a new file called "GET - httpgooglecom" for example, and you'd just "Save As".


Is this what you were looking for?

**Comment by ddavison** [comment]
closing this because of no response - hopefully that comment above helped.  if not, we can reopen the issue!

**Comment by netsi1964** [comment]
Hi @ddavison 
Thank you for your reply, and sorry for not replying before.

1. Tried your method: `https://jsonplaceholder.typicode.com/posts` 
2. Got the expected JSON in a new tab
3. Clicked "open in separate editor" => empty new tab (!)
4. Saved the file to a tmp file: `tmp\GET - jsonplaceholder.typicode.composts`

The file was empty... Did I do anything the wrong way?

If it had worked it would be a way to solve my request :-)

**Comment by ddavison** [comment]
![issue-64](https://cloud.githubusercontent.com/assets/2972876/19112834/012c7812-8ad5-11e6-9094-6906a16655b5.gif)

**Comment by netsi1964** [comment]
Great video! I see everything working perfectly on your computer... I am (here at work) on Windows 7, could that be the reason?
How do you make those GIFs btw? :-)

**Comment by ddavison** [comment]
OH, yes if you are using windows, then this issue could be related to #42

**Comment by netsi1964** [comment]
Ok, I will have to take it with my boss then :-) You may close it... (still would like to hear about how you record and create that GIF though :-)).

**Comment by ddavison** [comment]
I use LICEcap to record those gifs :)  http://www.cockos.com/licecap/. 

if you find the solution - please submit a PR as other people seem to have this problem 😕
