### ISSUE TITLE
saved requests are blown away

### ISSUE THREAD

**Issue by citizenrich** [ddavison/rest-client#69]
Seems with every update that the saved and recent requests disappear because they are stored in the package dir. Seems the only solution is to save off recents requests in any dir outside of the default, but I wonder if this is the preferred behavior.

**Comment by javaguirre** [comment]
too bad. :-(

I think the solution is probably having a directory `~/.atom-rest-client` with this data.

**Comment by citizenrich** [comment]
Indeed. Shall do.
