### ISSUE TITLE
How to open this?

### ISSUE THREAD

**Issue by gijo-varghese** [ddavison/rest-client#79]
Everything looks cool! But how to open this thing? It's mentioned nowhere!!!

**Comment by ddavison** [comment]
as with any other plugin on Atom, you have to open it by the pallet 👍 

Go ahead and press <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> if you're on Mac.  not sure what the shortcut is for windows.  (probably <kbd>Ctrl</kbd> instead of <kbd>Cmd</kbd>)

**Comment by gijo-varghese** [comment]
Ok. Thanks
