### ISSUE TITLE
Doc: How to start the rest-client

### ISSUE THREAD

**Issue by MJ97** [ddavison/rest-client#84]
For beginners like me would it be nice to know, how exactly to start that tool? 
I remember it was some kind of shortcut inside Atom, but I do not exactly remember how to get there again.

An update on the documentation for beginners would be highly appreciated.

Thank you!

**Comment by Rajdeep-TG** [comment]
Go to **Packages** -> **REST Client** -> **Show**

**Comment by ddavison** [comment]
I'm not sure there's much to do here 🤔 

Most of this information could be found in the [Atom Basics](https://flight-manual.atom.io/getting-started/sections/atom-basics/) documentation as to how to install the package and run it.  Closing.
