### ISSUE TITLE
How do I send a post request with a body?

### ISSUE THREAD

**Issue by sangeetds** [ddavison/rest-client#85]
Pretty new to API and stuff and so might not know the correct way. Was using postman before where I could send a post request consisting of a body, don't see any such option. Can somebody tell how to do so?

**Comment by pemasat** [comment]
Hi all,
i have same question. Has any body answer please?
Thank's a lot,
Petr

**Comment by ddavison** [comment]
> Pretty new to API and stuff and so might not know the correct way. Was using postman before where I could send a post request consisting of a body, don't see any such option. Can somebody tell how to do so?

There are two possibilities:

- Form multipart
- Raw Payload

The request would look like: `POST http://the-url.org/endpoint?a=foo&b=bar` to make a POST request sending parameters `a=foo` and `b=bar`.

If you needed to send a JSON payload, for instance, you could use the "Raw Payload" section and specify some json after setting the header `Content-Type: application/json`

```json
{ "a": "foo", "b": "bar" }
```
